---
jobs:
- name: publish
  public: true
  plan:
  - get: summit-training-classes
    trigger: true
  - task: generate
    file: summit-training-classes/operator/ci/build.yml
  - put: cf
    params:
      command: push
      strategy: rolling
      manifest: summit-training-classes/operator/ci/manifest.yml
      path: built/

resource_types:
- name: cf
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: summit-training-classes
  type: git
  source:
    uri: https://github.com/((github-org))/summit-training-classes.git
    branch: master
    paths:
    - operator/*

- name: cf
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    org: ((cf-organization))
    space: ((cf-space))
    cf_cli_version: 7
