resource_types:
- name: cf
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: summit-training-classes
  type: git
  source:
    branch: master
    uri: ((course-repository))
- name: cf
  type: cf
  source:
    api: ((cf-api))
    org: ((cf-org))
    password: ((cf-password))
    space: ((cf-space))
    username: ((cf-username))
    cf_cli_version: 7

jobs:
- name: publish
  public: true
  plan:
  - get: summit-training-classes
    trigger: true
  - task: generate
    file: summit-training-classes/basics/ci/build.yml
  - put: cf
    params:
      command: push
      strategy: rolling
      manifest: summit-training-classes/basics/ci/manifest.yml
      path: built/
      vars:
        routes: ((routes))
