resources:
- name: summit-training-classes
  type: git
  source:
    uri: https://github.com/((github-org))/summit-training-classes.git
    branch: master
    paths:
    - basics/*

- name: kf-pipelines
  type: git
  source:
    uri: git@github.com:EngineerBetter/kf-pipelines.git
    private_key: ((git_private_key))

jobs:
- name: publish
  public: true
  plan:
  - in_parallel:
    - get: summit-training-classes
      trigger: true
    - get: kf-pipelines
  - task: generate
    file: summit-training-classes/basics/ci/build.yml
  - task: generate-kubeconfig
    file: kf-pipelines/ci/tasks/generate-kubeconfig/task.yml
    params:
      GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
      REGION: ((ebkf-prod-app-developer-creds.region))
      CLUSTER: ((ebkf-prod-app-developer-creds.cluster_name))
  - &kf-task
    task: push-sample-app
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: built
      manifest: summit-training-classes
    params:
      ARGS: push --space production --manifest manifest/basics/ci/manifest.yml --path input --route zero-to-hero.engineerbetter.com
